-- Keep the production enum in sync with prisma/schema.prisma.
-- The schema gained these values without a corresponding database migration,
-- which caused every command that writes a gambling ledger entry to fail.
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'GAMBLING';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'GIFT_SENT';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'GIFT_RECEIVED';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'LOTTERY';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'SLOTS';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'COINFLIP';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'BLACKJACK';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'HIGHLOW';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'MINES';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'SNAILGARDEN';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'AUTOHUNT_COST';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'AUTOHUNT_REWARD';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'BATTLE_REWARD';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'QUEST_REWARD';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'CHECKLIST_REWARD';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'VOTE_REWARD';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'SHOP_PURCHASE';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'CRATE_PURCHASE';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'ADMIN_ADJUSTMENT';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'SACRIFICE';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'HUNT_COST';
ALTER TYPE "LedgerType" ADD VALUE IF NOT EXISTS 'HUNT_SALE';